// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFiles():Promise<Array<string>>;

export function ReadSaved(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;
